from __future__ import annotations

import argparse
import datetime as dt
import shutil
import subprocess
import sys
from pathlib import Path


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def find_ffmpeg() -> str:
    ffmpeg = shutil.which("ffmpeg")
    if ffmpeg:
        return ffmpeg
    try:
        import imageio_ffmpeg

        return imageio_ffmpeg.get_ffmpeg_exe()
    except Exception as exc:
        raise RuntimeError("ffmpeg was not found. Install ffmpeg or imageio-ffmpeg.") from exc


def run_command(args: list[str], cwd: Path | None = None) -> None:
    print("")
    print(" ".join(f'"{item}"' if " " in item else item for item in args))
    subprocess.run(args, cwd=cwd, check=True)


def ffconcat_path(path: Path) -> str:
    """Return a path string suitable for ffmpeg concat demuxer files."""
    return path.resolve().as_posix().replace("'", "'\\''")


def write_stereo_concat_list(
    stereo_frames: list[Path],
    concat_list_path: Path,
) -> None:
    lines = ["ffconcat version 1.0"]
    for frame_path in stereo_frames:
        lines.append(f"file '{ffconcat_path(frame_path)}'")
    concat_list_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def default_output_dir(root: Path) -> Path:
    stamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    return root / "outputs" / f"video_vr_{stamp}"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Video -> frames -> SHARP PLY -> stereo SBS frames -> VR SBS mp4 pipeline."
    )
    parser.add_argument("-i", "--input-video", required=True, type=Path)
    parser.add_argument("-o", "--output-dir", type=Path)
    parser.add_argument("--fps", type=float, default=30.0)
    parser.add_argument("--ipd", type=float, default=0.064)
    parser.add_argument("--crf", type=int, default=18)
    parser.add_argument("--max-frames", type=int, default=0)
    parser.add_argument(
        "--start-seconds",
        type=float,
        default=0.0,
        help="Start extracting frames from this timestamp in seconds.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = project_root()
    input_video = args.input_video.resolve()
    output_dir = (args.output_dir or default_output_dir(root)).resolve()
    frames_dir = output_dir / "01_frames"
    ply_dir = output_dir / "02_ply"
    stereo_frames_dir = output_dir / "03_stereo_frames"
    concat_list_path = output_dir / "stereo_frames.ffconcat"
    final_video = output_dir / "vr_sbs.mp4"
    sharp = root / ".venv" / "Scripts" / "sharp.exe"

    if not input_video.exists():
        raise FileNotFoundError(f"Input video not found: {input_video}")
    if not sharp.exists():
        raise FileNotFoundError(f"SHARP CLI not found: {sharp}")

    output_dir.mkdir(parents=True, exist_ok=True)
    frames_dir.mkdir(parents=True, exist_ok=True)
    ply_dir.mkdir(parents=True, exist_ok=True)
    stereo_frames_dir.mkdir(parents=True, exist_ok=True)

    ffmpeg = find_ffmpeg()
    fps_filter = f"fps={args.fps}"
    if args.max_frames > 0:
        fps_filter = f"{fps_filter},select=lte(n\\,{args.max_frames - 1})"

    print("Video to VR SBS pipeline")
    print(f"Input:         {input_video}")
    print(f"Output:        {output_dir}")
    print(f"FPS:           {args.fps}")
    print(f"IPD:           {args.ipd}")
    print(f"Start:         {args.start_seconds} seconds")
    print(f"Frame limit:   {args.max_frames or 'none'}")

    extract_command = [ffmpeg, "-y"]
    if args.start_seconds > 0:
        extract_command += ["-ss", str(args.start_seconds)]
    extract_command += [
        "-i",
        str(input_video),
        "-vf",
        fps_filter,
        str(frames_dir / "frame_%06d.png"),
    ]
    run_command(extract_command, cwd=root)

    extracted_frames = sorted(frames_dir.glob("frame_*.png"))
    if not extracted_frames:
        raise RuntimeError("No frames were extracted from the input video.")

    run_command(
        [
            str(sharp),
            "predict",
            "-i",
            str(frames_dir),
            "-o",
            str(ply_dir),
            "--device",
            "cuda",
        ],
        cwd=root,
    )

    ply_files = sorted(ply_dir.glob("*.ply"))
    if not ply_files:
        raise RuntimeError("No PLY files were generated by SHARP.")

    run_command(
        [
            str(sharp),
            "render-stereo-frames",
            "-i",
            str(ply_dir),
            "-o",
            str(stereo_frames_dir),
            "--ipd",
            str(args.ipd),
        ],
        cwd=root,
    )

    stereo_frames = sorted(stereo_frames_dir.glob("*.sbs.png"))
    if not stereo_frames:
        raise RuntimeError("No SBS stereo frames were generated.")

    write_stereo_concat_list(stereo_frames, concat_list_path)

    encode_command = [
        ffmpeg,
        "-y",
        "-r",
        str(args.fps),
        "-f",
        "concat",
        "-safe",
        "0",
        "-i",
        str(concat_list_path),
    ]
    if args.start_seconds > 0:
        encode_command += ["-ss", str(args.start_seconds)]
    encode_command += [
        "-i",
        str(input_video),
        "-map",
        "0:v:0",
        "-map",
        "1:a?",
        "-c:v",
        "libx264",
        "-pix_fmt",
        "yuv420p",
        "-r",
        str(args.fps),
        "-crf",
        str(args.crf),
        "-c:a",
        "aac",
        "-shortest",
        str(final_video),
    ]
    run_command(encode_command, cwd=root)

    print("")
    print("Done.")
    print(f"Frames:        {len(extracted_frames)}")
    print(f"PLY files:     {len(ply_files)}")
    print(f"SBS frames:    {len(stereo_frames)}")
    print(f"VR video:      {final_video}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except subprocess.CalledProcessError as exc:
        print(f"Command failed with exit code {exc.returncode}", file=sys.stderr)
        raise SystemExit(exc.returncode)
